apiVersion: v1
kind: ServiceAccount
metadata:
  name: podtato-head-hello-server
  labels:
    helm.sh/chart: hello-server-0.1.0
    app.kubernetes.io/name: hello-server
    app.kubernetes.io/instance: podtato-head
    app.kubernetes.io/version: "v0.1.2"
    app.kubernetes.io/managed-by: Helm
