---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: gitops-repo
  namespace: flux-system
spec:
  interval: 15s
  ref:
    branch: main
  secretRef:
    name: gitops-repo
  url: ssh://git@github.com/rmortale/civo-gitops
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: gitops-repo
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./production
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-repo
  validation: client
